from lxml import htmlfrom lxml.html.clean import clean_htmlfrom urlparse import urlparse
def _get_favicon(doc):    return _get_data(doc, path=["link"], selector={'rel':'shortcut icon'}, field='href')[0]def _get_selector(selector):    pairs = ("@%s='%s'" % (k, v) for k,v in selector.iteritems())
    return "[%s]" % (" and ".join(pairs))def _get_meta(doc, selector, first=True):    """Get metadata from the html.    Arguments:    doc -- The HTML element to grab metadata from.    first -- True if the first result should be automatically returned.    selector -- A dictionary of html selectors.    Examples:    _get_meta(doc, {'name':'news_keywords'})    _get_meta(doc, {'property':'article:modified'})    Return a list of all elements that match the selectors or just the first one.    """    result = _get_data(doc, path=["meta"], selector=selector, field="content")    if first:        return result[0]    else:        return resultdef _get_data(doc, path=[], selector=None, field=None):    """    Get all Elements at the given path.    Arguments:    doc -- The HTML element to extract data from.    path -- A list of the path components to the desired element.    Examples:    _get_data(doc, ["body", "article", "p"])    Return a list of all elements that match the path.    """    path_text = "//%s" % "//".join(path)    if selector is not None:        selector_text = _get_selector(selector)    else:        selector_text = ""    if field is not None:        field_text = "/@%s" % field    else:        field_text = ""        return doc.xpath("%s%s%s" % (path_text, selector_text, field_text))
def parse_cnn_article(article):
    # This alters the html in-place.
    clean_html(article.html)
    doc = html.document_fromstring(article.html)    if _get_meta(doc, {'name': 'medium'}) == "video":        raise ValueError("Cannot parse a video article.")    text = _get_data(doc, ["body", "div", "div", "div", "p"])    text = "\n".join(t.text for t in text if t.text is not None)    article.text = text    article.title = _get_meta(doc, {'itemprop': 'headline'})    article.categories = [_get_meta(doc, {'itemprop': 'articleSection'})]    article.categories.extend(_get_meta(doc, {'itemprop': 'subsection'}, first=False))    article.pub_date = _get_meta(doc, {'itemprop': 'dateModified'})    article.authors = _get_meta(doc, {'itemprop': 'author'})    article.location = _get_meta(doc, {'itemprop': 'contentLocation'})    article.summary = _get_meta(doc, {'itemprop': 'description'})    # Page doesn't link to a favicon so just assume the default.    article.meta_favicon = article.source_domain + "/favicon.ico"    article.meta_lang = _get_meta(doc, {'itemprop': 'inLanguage'})    # location is sometimes not provided.    if article.location == "":        article.location = None

def parse_nytimes_article(article):    # This alters the html in-place.    clean_html(article.html)    doc = html.document_fromstring(article.html)    text = _get_data(doc, ["body", "article", "p"])    text = "\n".join(t.text for t in text if t.text is not None)    article.text = text    article.title = _get_meta(doc, {'property': 'og:title'})    keywords = _get_meta(doc, {'name': "news_keywords"})    article.keywords = keywords.split(';')    article.pub_date = _get_meta(doc, {'property': 'article:modified'})    article.authors = _get_meta(doc, {'name': 'author'}, first=False)    #Not always present    try:        article.location = _get_meta(doc, {'name': 'geo'})    except:        article.location = None    article.summary = _get_meta(doc, {'itemprop': 'description'})    article.meta_favicon = _get_favicon(doc)    article.meta_lang = _get_meta(doc, {'itemprop': 'inLanguage'})
    #TODO: Get title image out of the article.    #TODO: Get suggested articles out of the article.